#pragma once

#define FC_TARGET_MCU RP2350A
#define BOARD_NAME PICO_CUSTOM
#define MANUFACTURER_ID RASP

// bmi160
#define USE_ACC
#define USE_GYRO
#define USE_SPI_GYRO
#define USE_ACCGYRO_BMI160

#define SPI1_SCK_PIN PA10
#define SPI1_SDI_PIN PA12
#define SPI1_SDO_PIN PA11

#define GYRO_1_CS_PIN PA13
#define GYRO_1_SPI_INSTANCE SPI1
#define GYRO_1_ALIGN CW0_DEG

// motors
#define MOTOR1_PIN PA2
#define MOTOR2_PIN PA3
#define MOTOR3_PIN PA4
#define MOTOR4_PIN PA5

// receiver
#define PIOUART0_TX_PIN PA0
#define PIOUART0_RX_PIN PA1

// gps + magnetometer
#define USE_GPS
#define USE_GPS_PLUS_CODES
#define UART1_TX_PIN PA8
#define UART1_RX_PIN PA9
#define GPS_UART SERIAL_PORT_UART1

#define USE_MAG
#define I2C1_SDA_PIN PA6
#define I2C1_SCL_PIN PA7
#define MAG_I2C_INSTANCE I2CDEV_1

// bmp280
#define USE_BARO
#define USE_BARO_SPI_BMP280
#define SPI0_SCK_PIN PA18
#define SPI0_SDI_PIN PA20
#define SPI0_SDO_PIN PA19
#define BARO_CS_PIN PA21
#define BARO_SPI_INSTANCE SPI0
